import 'package:flutter/material.dart';        // Flutter UI framework — needed for every screen
import 'package:google_fonts/google_fonts.dart'; // lets us use custom fonts like Inter and Orbitron
import 'package:firebase_core/firebase_core.dart'; // required to initialize Firebase before using any Firebase service
import 'firebase_options.dart';                // auto-generated by FlutterFire CLI — contains your Firebase project config
import 'screens/splash_screen.dart';           // first screen shown on launch

// ─────────────────────────────────────────────────────────────────────────────
// main.dart — the entry point of the entire app.
// Flutter always starts here. We initialize Firebase first, then launch the UI.
// ─────────────────────────────────────────────────────────────────────────────

void main() async {
  // Required before any async work in main().
  // Ensures Flutter's engine is fully ready before we touch Firebase.
  WidgetsFlutterBinding.ensureInitialized();

  // Connect the app to your Firebase project using the generated config file.
  // Must complete before any screen tries to read/write to Firebase.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // picks the right config for web/android/ios
  );

  // Launch the app. Everything from here is driven by Flutter widgets.
  runApp(const MyApp());
}

// MyApp is the root widget — wraps everything in MaterialApp which provides
// navigation, theming, and all Material Design components used in the app.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false, // hides the red DEBUG banner in the corner
      title: 'Fluffy Friends',           // app name shown in the OS task switcher
      theme: ThemeData(
        // Sets Inter as the default font for all Text widgets throughout the app
        fontFamily: GoogleFonts.inter().fontFamily,
      ),
      // SplashScreen is the first thing shown — it checks if the user is already
      // logged in and routes to either the feed or the login screen
      home: const SplashScreen(),
    );
  }
}
